Controllers/PlantsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using LeafLINQWeb.Filters;
using Newtonsoft.Json;
using System.Net;
using System.Text;
using LeafLINQWeb.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using LeafLINQWeb.Utilities;

namespace LeafLINQWeb.Controllers;

[AuthorizeUser]
public class PlantsController : Controller
{

    private readonly IHttpClientFactory _clientFactory;
    private readonly BlobStorageService _blobStorageService;
    private HttpClient Client => _clientFactory.CreateClient("api");
    private HttpClient PlantClient => _clientFactory.CreateClient("api-plant-data");

    public PlantsController(IHttpClientFactory clientFactory, BlobStorageService blobStorageService)
    {
        _clientFactory = clientFactory;
        _blobStorageService = blobStorageService;
    }

    // --------------
    // Plants
    // --------------
    [HttpGet]
    public async Task<IActionResult> Index(string search = null, int page = 1)
    {
        // Check if admin, if admin get all plants. If regular user get only relevant plants
        HttpResponseMessage response;
        if (HttpContext.Session.GetString(SessionKeys.UserType).Equals("A") ||
            HttpContext.Session.GetString(SessionKeys.UserType).Equals("S"))
        {
            // Make the API request to retrieve all users plants
            response = await Client.GetAsync("api/Plants/allPlants");
        }
        else
        {
            // Make the API request to retrieve this users plants
            response = await Client.GetAsync("api/Plants/plants");
        }

        // Check if the request was successful
        if (response.IsSuccessStatusCode)
        {
            // Read and deserialize the response content
            var result = await response.Content.ReadAsStringAsync();
            var plants = JsonConvert.DeserializeObject<List<PlantModel>>(result);

            // Filter plants based on search parameter
            if (!string.IsNullOrEmpty(search))
            {
                plants = plants.Where(p =>
                    p.Name.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                    p.Location.Contains(search, StringComparison.OrdinalIgnoreCase)
                ).ToList();
            }

            // Pagination
            int pageSize = 10;
            int itemsToSkip = (page - 1) * pageSize;
            var nextPage = plants.OrderBy(b => b.LastWateredDate).Skip(itemsToSkip).Take(pageSize).ToList();

            ViewBag.CurrentPage = page;
            ViewBag.TotalNumberOfItems = plants.Count();

            nextPage = await GetPlantHealthCheckStatus(nextPage);

            return View(nextPage);
        }
        else
        {
            ModelState.AddModelError("Error", "Error retrieving plant list");
            return View();
        }
    }


    public async Task<List<PlantModel>> GetPlantHealthCheckStatus(List<PlantModel> plants)
    {
        foreach (var plant in plants)
        {
            var plantSensorReadings = await GetPlantSensorReadings(plant.Id);

            if (plantSensorReadings != null)
            {
                var latestReading = plantSensorReadings.OrderByDescending(r => DateTime.Parse(r.timestamp)).FirstOrDefault();

                if (latestReading != null)
                {
                    plant.UpdateHealthStatus(latestReading);
                }

            }

        }
        return plants;
    }

    public async Task<List<PlantSensorReadings>> GetPlantSensorReadings(int plantId)
    {
        try
        {
            var response = await PlantClient.GetAsync($"/api/SensorReadings/plant/{plantId}");

            if (response.IsSuccessStatusCode)
            {
                var result = await response.Content.ReadAsStringAsync();
                return JsonConvert.DeserializeObject<List<PlantSensorReadings>>(result);
            }
            else
            {
                return null;
            }
        }
        catch (Exception ex)
        {
            throw ex;
        }
    }

    // --------------
    // Plant
    // --------------
    [HttpGet]
    public async Task<IActionResult> Plant(int id)
    {
        // Make the API request to retrieve users
        var response = await Client.GetAsync($"api/Plants/plant?id={id}");

        // Check if the request was successful
        if (response.IsSuccessStatusCode)
        {
            // Read and deserialize the response content
            var result = await response.Content.ReadAsStringAsync();
            var plant = JsonConvert.DeserializeObject<PlantModel>(result);

            // Build reports
            var reports = await BuildReports(id);

            if (reports != null)
            {
                plant.PlantReport = reports;
            }

            // Device Sensor 
            var sensorStatus = await GetSensorStatusAsync(id);

            if(sensorStatus != null)
            {
                plant.DeviceAPISensorStatusRequest = GetMostRecentSensorData(sensorStatus);
            }


            if (HttpContext.Session.GetString(SessionKeys.UserType).Equals("A") || 
                HttpContext.Session.GetString(SessionKeys.UserType).Equals("S"))
            {
                plant.UserSelectList = await GetUserSelectListAsync();
                plant.PlantDeviceList = await GetDeviceSelectListAsync();
            }


            return View(plant);
        }
        else
        {
            ModelState.AddModelError("Error", "Error Retireving plant List");
            return View();
        }
    }


    [HttpGet]
    public async Task<PlantAPISensorReadingAverage> GetDailyReports(int plantId)
    {
        // Send the GET request and await the response
        var response = await PlantClient.GetAsync($"/api/SensorReadings/plant/{plantId}");

        if (response.IsSuccessStatusCode)
        {
            var result = await response.Content.ReadAsStringAsync();
            // Deserialize the result into a list of sensor reading models
            var allReports = JsonConvert.DeserializeObject<List<PlantAPISensorReadingModel>>(result);

            // Find the most recent report based on the Timestamp
            var mostRecentReport = allReports.OrderByDescending(x => x.Timestamp).FirstOrDefault();

            if (mostRecentReport != null)
            {
                // Convert timestamp to start and end of that day
                DateTime timestamp = mostRecentReport.Timestamp;

                // Get the start of the day (00:00:00)
                DateTime startOfDay = timestamp.Date;

                // Get the end of the day (23:59:59)
                DateTime endOfDay = timestamp.Date.AddDays(1).AddSeconds(-1);

                // Format the startOfMonth and endOfMonth using the ISO 8601 format
                string formattedStartTime = startOfDay.ToString("yyyy-MM-ddTHH:mm:ss");
                string formattedEndTime = endOfDay.ToString("yyyy-MM-ddTHH:mm:ss");

                var dailyReport = await GetAverageSensorReadingsByPlant(plantId, formattedStartTime, formattedEndTime);

                return dailyReport;

            }
            else
            {
                // Handle the case where there are no reports
                return null;
            }
        }
        else
        {
            // Handle the case where the response is not successful
            return null;
        }
    }

    [HttpGet]
    public async Task<List<PlantAPISensorReadingDailyAverage>> GetMonthlyReports(int plantId)
    {
        var dailyAverages = await GetDailyAverageSensorReadingsByPlant(plantId, 30);

        return dailyAverages;
    }

    public async Task<ReportsModel> BuildReports(int id)
    {
        var reports = new ReportsModel
        {
            DailyReports = await GetDailyReports(id),
            MonthlyReports = await GetMonthlyReports(id)
        };
        return reports;
    }

    public async Task<List<SelectListItem>> GetDeviceSelectListAsync()
    {

        List<SelectListItem> deviceList = new List<SelectListItem>();
        // Make the API request to retrieve all plants
        var response = await PlantClient.GetAsync($"api/Devices/UnassignedPlantNodes");

        // Check if the request was successful
        if (response.IsSuccessStatusCode)
        {
            // Read and deserialize the response content
            var result = await response.Content.ReadAsStringAsync();
            var devices = JsonConvert.DeserializeObject<List<PlantAPIDeviceModel>>(result);

            foreach (var device in devices)
            {

                SelectListItem selectListItem = new SelectListItem()
                {
                    Value = device.deviceId.ToString(),
                    Text = device.deviceId.ToString(),
                };
                deviceList.Add(selectListItem);

            }

        }

        return deviceList;
    }

    // Average readings report with {plant id, start time, end time}
    [HttpGet]
    public async Task<List<PlantAPISensorReadingDailyAverage>> GetDailyAverageSensorReadingsByPlant(int plantId, int numberOfDays)
    {

        // Construct the query string with the formatted date-time parameters
        var queryString = $"api/Reporting/sensorreadings/dailyaverage/plant?plantId={plantId}&numberOfDays={numberOfDays}";

        // Send the GET request with the query string
        var response = await PlantClient.GetAsync(queryString);

        if (response.IsSuccessStatusCode)
        {
            var results = await response.Content.ReadAsStringAsync();
            var report = JsonConvert.DeserializeObject<List<PlantAPISensorReadingDailyAverage>>(results);
            return report;
        }
        else
        {
            return null;
        }
    }


    // Average readings report with {plant id, start time, end time}
    [HttpGet]

Views/Plants/AddPlant.cshtml
@model LeafLINQWeb.Models.PlantModel;

<div class="main-page">
    @Html.Partial("_Sidebar")
    <div class="main-content">
        <div class="main-header">
            <h2>Plants</h2>
            <a class="btn primary" asp-controller="Plants" asp-action="AddPlant"><i class="fa-solid fa-circle-plus"></i> Add Plant</a>
        </div>
        @using (Html.BeginForm("AddNewPlant", "Plants", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="container">
                <div class="column">
                    <div class="error">@ViewBag.Error</div>
                    <div class="user-input">
                        @Html.LabelFor(model => model.Name)
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                    <div class="user-input">
                        @Html.LabelFor(model => model.Desc)
                        @Html.TextAreaFor(model => model.Desc, new { @class = "form-control", required = "required", rows = "4" })
                        @Html.ValidationMessageFor(model => model.Desc)
                    </div>
                    <div class="user-input">
                        @Html.LabelFor(model => model.Location)
                        @Html.TextBoxFor(model => model.Location, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.Location)
                    </div>
                    <input class="btn primary" type="submit" value="Submit" />
                </div>
                <div class="column">
                    <div class="user-input">
                        @Html.LabelFor(model => model.ImageFile)
                        <input type="file" class="form-control profile-file" id="picture" name="ImageFile" accept="image/*">
                    </div>
                    <div class="user-input">
                        @Html.LabelFor(model => model.Level)
                        @Html.TextBoxFor(model => model.Level, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.Level)
                    </div>
                    <div class="user-input">
                        @Html.LabelFor(model => model.DeviceId)
                        @Html.ValidationMessageFor(model => model.DeviceId)
                        <br />
                        <select asp-for="@Model.DeviceId" asp-items="Model.PlantDeviceList" class="form-control"></select>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Plants/Index.cshtml
@model List<LeafLINQWeb.Models.PlantModel>;

@{
    ViewData["Title"] = "Plants";

    int totalPlants = ViewBag.TotalNumberOfItems;
    int skipItems = 10;
    double totalPages = (double)totalPlants / skipItems;
    int roundedTotalPages = (int)Math.Ceiling(totalPages);
 }


<div class="main-page">
    @Html.Partial("_Sidebar")
    <div class="main-content">

        <div class="main-header">
            <h2>Plants</h2>
            <a class="btn primary" asp-controller="Plants" asp-action="AddPlant"><i class="fa-solid fa-circle-plus"></i> Add Plant</a>
        </div>

        <div class="container">
            <div class="column">
                <div class="main-table-container">
                    <div class="main-table-header">
                        <h4>Your Plants</h4>
                        <form method="get" asp-controller="Home" asp-action="Index" class="search-bar">
                            <input type="text" name="search" id="searchInput" placeholder="Search name and location...">
                            <button type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                        </form>
                    </div>
                    <table class="main-table">
                        <thead>
                            <tr>
                                <th>Plant Name</th>
                                <th>Location</th>
                                <th>Last Watered Date</th>
                                <th>Health Check Status</th>
                                <th>Download Report</th>    
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var plant in Model)
                            {
                                <tr>
                                    <td><a href="@Url.Action("Plant", "Plants", new { id = plant.Id })">@plant.Name</a></td>
                                    <td>@plant.Location</td>
                                    <td>@plant.LastWateredDate.ToShortDateString()</td>
                                        <td class="status-circle @(plant.HealthCheckStatus.ToString().ToLower())">@plant.HealthCheckStatus</td>
                                    <td><a href="@Url.Action("Plant", "Plants", new { id = plant.Id })">Reports <i class="fa-solid fa-download"></i></a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div class="main-table-footer">
                        @{
                            PaginationModel paginationModel = new PaginationModel()
                            {
                                CurrentPage = ViewBag.CurrentPage,
                                TotalPages = roundedTotalPages,
                                PageSize = skipItems
                            };
                        }
                        @Html.Partial("_Pagination", paginationModel)
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>